import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json({ limit: '10mb' }));

  const ai = new GoogleGenAI({
    apiKey: process.env.GEMINI_API_KEY || "",
    httpOptions: {
      headers: {
        'User-Agent': 'aistudio-build',
      }
    }
  });

  // API Routes
  app.get("/api/gemini/status", (req, res) => {
    res.json({ hasKey: !!process.env.GEMINI_API_KEY });
  });

  app.post("/api/gemini/generate-image", async (req, res) => {
    try {
      const { title, content } = req.body;
      
      if (!process.env.GEMINI_API_KEY) {
        return res.status(400).json({ error: "Gemini API key is not configured. Please add it in Settings > Secrets." });
      }

      const prompt = `Generate a serene and artistic cover image for a journal entry. 
Title: ${title}
Content: ${content}

The image should be minimalist, expressive, and fit the mood of the entry. No text in the image.`;

      const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
          parts: [{ text: prompt }],
        },
        config: {
          imageConfig: {
            aspectRatio: "16:9",
          }
        }
      });

      let base64Image = "";
      for (const part of response.candidates?.[0]?.content?.parts || []) {
        if (part.inlineData) {
          base64Image = part.inlineData.data;
          break;
        }
      }

      if (!base64Image) {
        throw new Error("No image was generated by the model.");
      }

      res.json({ imageData: base64Image });
    } catch (error: any) {
      console.error("Gemini Error:", error);
      
      // Handle Quota/Paid Model errors gracefully
      if (error.status === 429 || (error.message && error.message.includes("quota"))) {
        return res.status(429).json({ 
          error: "QUOTA_EXHAUSTED",
          message: "You've reached the free tier limit for image generation or this model requires a paid API key. Please check your Gemini API billing in Settings > Secrets."
        });
      }

      res.status(500).json({ 
        error: error.message || "Failed to generate image",
        details: error.status === 403 ? "This model requires a paid API key. Please check your billing settings." : undefined
      });
    }
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
